---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chatbot-secrets
  namespace: chatbot
spec:
  encryptedData:
    LLM_API_KEY: AgBmoMf9NcnSMOLq5VB4GtQ/8vmdHm7X8H3z6CbrpadB/IQcjrt8cs0ez1d7UQsrQkBKr58eIqCK9e7ByV1gTLG5ezhfo725tCPYkD1tKCMkka7DAP7LSgMNcJOPuo0JP6B10l96vofOj6mP37b2a0rg8/xb21UEaSnqhnXH2KFuhv+QhZ7LiS0BkbIbOrjGetj1lOkKceZ6S2NC2hZ1dMF6qtmWh1tnY+8rkaDTa8tiIC07UGWTi02KkKzx7B4kcYsopJ8qGKkepUbwS9qoci6CpfAZBIsrwU3y1rC2SCPYHV9uVQUBTdZOSezPCYK/XY0BFHdu30NHfaI/DImSn5Q11NnVPkznXKXtW3WqYLh2XOUYuhr3Y+UiA0usguRjGSOQ/io7HodubRnkAmcgWqkcOLvFqIwCjzb3aDR/Z2urq5FzlyCxngbiM6illC6HfF7/6kHqDih7Oc921uJZW//EvxVYfnAHe/i+pDJVCDfSgBZF+r/ep5g8isTo60wnLVz5hj+NuKOAUD0Mdh+Pg5MpouOYPkHm/kZfD9Ay+D44Qf70OpgXYDhLSoKxXw+TErbcDLQmcztQIKQHELAzquxQaJih1xWY3sdTbXjiyyTlsjCOSilo9BPVJbamyMwT1kxer92K8/Iq8AZ55quwwmlf5o+R8LkJ05c1pu5zBZjugfUvZUVJGv29yP7iVIO6x0Ka3S2HN2MY9xFnOjURa5lIVX6e7O93CmQIopWWB9g2NJl/vafDukedHmO/p6d8dcynccf/IjTU0Q==
  template:
    metadata:
      name: chatbot-secrets
      namespace: chatbot
